service: ${self:custom.serviceName}
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: launchmotion-sls-functions

functions:
  getPaginatedRows:
    handler: src/main.getPaginatedRows
    description: Leitura de dados com paginação
    events:
      - httpApi:
          method: GET
          path: /list
  getAllRows:
    handler: src/main.getAllRows
    description: Leitura de dados sem paginação
    events:
      - httpApi:
          method: GET
          path: /listAll
  addRows:
    handler: src/main.addRows
    description: Registro de dados
    events:
      - httpApi:
          method: POST
          path: /add
  removeRows:
    handler: src/main.removeRows
    description: Remoção de dados
    events:
      - httpApi:
          method: DELETE
          path: /remove

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv
  - serverless-deployment-bucket

custom:
  serviceName: ${env:SERVICE_NAME, 'default-service-name'}
  webpack:
    webpackConfig: 'webpack.config.js'
  serverless-offline:
    useChildProcess: true
    httpPort: 3001
