service: sls-email-sender
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128
  timeout: 3
  environment:
    FROM_ADDRESS: ${env:FROM_ADDRESS}
  deploymentBucket:
    name: launchmotion-sls-functions
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "arn:aws:ses:us-east-1:576679484800:identity/*"

functions:
  sendEmail:
    handler: src/main.sendEmail
    description: Envio de emails
    events:
      - httpApi:
          method: POST
          path: /send-email/{type}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv
  - serverless-deployment-bucket

custom:
  webpack:
    webpackConfig: "webpack.config.js"
  serverless-offline:
    useChildProcess: true
    httpPort: 3000
