export const envs = {
  GOOGLE_SPREAD_SHEET_KEY: process.env.GOOGLE_SPREAD_SHEET_KEY,
  GOOGLE_SPREAD_SHEET_CLIENT_EMAIL:
    process.env.GOOGLE_SPREAD_SHEET_CLIENT_EMAIL,
  GOOGLE_SPREAD_SHEET_PRIVATE_KEY: process.env.GOOGLE_SPREAD_SHEET_PRIVATE_KEY,
};
